---
datacenter:
  children:
    routers:
      hosts:
        R5-1:
          ansible_host: 10.215.28.193
        R5-2:
          ansible_host: 10.215.28.192

  vars:
    ansible_become_password: vnpro#321
    ansible_user: xxxx
    ansible_password: xxxxx
    ansible_connection: network_cli
    ansible_become: "yes"
    ansible_become_method: "enable"
    ansible_network_os: ios



---
- name: dat ip cho Lo0
  hosts: R1
  gather_facts: False
  tasks:
    - name: Set Ipv4 address
      ios_l3_interface:
        name: loopback {{ item.name }}
        ipv4: 7.7.{{ item.number}}.7/24
      with_items:
        - { name: "0", number: 7}
    - name: Save configure
      ios_command:
        commands:
          - write memory
          - show ip int br